steps:
 
  - name: 'golang'
    args: ['install', '.']
    env: ['PROJECT_ROOT=hello']
    dir: 'src'

  # - name: 'golang'
  #   args: 
  #     - 'install'
  #   env: 
  #     - 'PROJECT_ROOT=hello'
#      - 'GOPATH=/src'

#  - name: 'golang'
#    args:
#      - 'test'
#      - 'hello'
#    env:
#      - 'PROJECT_ROOT=hello'
#      - 'GOPATH=./src/'
#
#  - name: 'docker'
#    id: 'Build'
#    args:
#      - 'build'
#      - '-t'
#      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
#      - '-f'
#      - './src/Dockerfile'
#      - '.'
#
#  - name: "docker"
#    id: "Run"
#    args:
#      - "run"
#      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
