steps:
 
  - name: 'gcr.io/cloud-builders/go'
    args: 
      - 'install' 
      - '.'
    env: 
      - 'PROJECT_ROOT=hello'
    dir: 'src'

  - name: 'gcr.io/cloud-builders/go'
    args:
      - 'test'
      - '-v'
      - 'hello'
    env:
      - 'PROJECT_ROOT=hello'
    dir: 'src'
#
#  - name: 'docker'
#    id: 'Build'
#    args:
#      - 'build'
#      - '-t'
#      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
#      - '-f'
#      - './src/Dockerfile'
#      - '.'
#
#  - name: "docker"
#    id: "Run"
#    args:
#      - "run"
#      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
