steps:
 
  - name: 'golang'
    args: 
      - 'install' 
      - './src/'
    env: 
      - 'PROJECT_ROOT=hello'

  - name: 'golang'
    args: 
      - 'test'
      - 'hello'
    env: 
      - 'PROJECT_ROOT=hello'

  - name: 'docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
      - '-f'
      - './src/Dockerfile'
      - '.'

  - name: "docker"
    id: "Run"
    args: 
      - "run"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"

    # args: 
    #   - "test"
    #   - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"

  # - name: "docker"
  #   id: "Test"
  #   args: ["exec", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA", "go", "test", "-v"]

  # - name: 'docker'
  #   id: 'Push'
  #   args:
  #     - 'push'
  #     - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
