steps:
  - name: 'docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
      - '-f'
      - './src/Dockerfile'
      - '.'

  - name: "docker"
    id: "Run"
    args: 
      - "run"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"

  - name: "golang"
    id: "Test"
    args: ['test', '-v']
    env: ['GOPATH=.']
    # args: 
    #   - "test"
    #   - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"

  # - name: "docker"
  #   id: "Test"
  #   args: ["exec", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA", "go", "test", "-v"]

  # - name: 'docker'
  #   id: 'Push'
  #   args:
  #     - 'push'
  #     - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
