steps:
  - name: 'docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
      - '-f'
      - './src/Dockerfile'
      - '.'

  - name: "docker"
    id: "Test"
    args: ["exec", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA", "go", "test", "-v"]

  - name: 'docker'
    id: 'Push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
